INSERT INTO communities (name, description, location, cause, creation_date, picture_url)
VALUES
  ('Homesteading', 'A lifestyle choice for individuals or families who aim for self-sufficiency by growing our own food, raising livestock, and becoming more independent from modern amenities and commercial goods. We practice sustainable living, renewable energy use, and various DIY (do-it-yourself) skills to reduce reliance on external resources.', 'Location A', 2, '2023-01-15', 'https://images.ctfassets.net/pujs1b1v0165/7dCa9XiclWMg0y118t23SN/5a38d993e615a3d187348e60206243a6/How_to_Plan_a_Homestead.jpg'),
  ('Food Insecurity', 'Helping individuals, families, or entire communities overcome food insecurity. Food insecurity is the lack of consistent access to enough food for an active, healthy life for all household members. It is caused by various factors, including poverty, unemployment, low wages, lack of access to fresh and nutritious food, and social or political instability.', 'Location B', 3, '2023-02-20', 'https://training-conditioning.com/wp-content/uploads/2022/08/EXZCK2XADZJ5JB2PHSFURR45SM-768x432.jpeg'),
  ('Digital Literacy', 'Digital literacy is essential for full participation in society, the economy, and education. Lack of digital literacy can create significant barriers in this technology-driven world. It can limit access to information, job opportunities, education, healthcare services, and social interactions', 'Location C', 3, '2023-02-20', 'https://theeducationdaily.com/wp-content/uploads/2023/02/Digital-literacy-and-media-education.jpg'),
  ('Political Reform', 'Advocating for political reform aims to create more transparent, accountable, and responsive political systems. This can include campaigns for electoral reform, anti-corruption measures, and increased citizen participation in decision-making processes.', 'Location C', 1, '2023-10-20', 'https://d1y8sb8igg2f8e.cloudfront.net/images/shutterstock_21965417492.width-600.png'),
   ('Public Services', 'Grassroots movements focused on public services advocate for accessible, affordable, and high-quality services such as healthcare, education, transportation, and utilities. These movements often engage in community organizing, awareness campaigns, and advocacy efforts to improve public services. They work to ensure that essential services are available to all members of the community, particularly those in underserved or marginalized areas. Grassroots activists may also collaborate with local authorities, initiate petitions, and organize protests to address gaps in public services and promote social equity. Through their efforts, these movements aim to create positive change, enhance community well-being, and advocate for the fair distribution of resources.', 'Location C', 1, '2023-10-20', 'https://pop-umbrella.s3.amazonaws.com/uploads/image/425fb950-d4ef-46a5-97a1-18afbc3ad9ac_coverpage_0_featured.jpg'),
   ('Peace and Anti-War', 'Grassroots peace movements employ nonviolent protests, social media campaigns, and cultural events to raise awareness about impacts of war and advocate for peaceful solutions. They promote dialogue, diplomacy, and disarmament, organizing marches and rallies to mobilize public support. These movements also engage in education efforts, artistic expression, interfaith dialogue, and lobbying to inspire change, shape public opinion, and foster a global culture of peace and understanding.', 'Location C', 1, '2023-10-20', 'https://static01.nyt.com/images/2019/11/08/magazine/08atwar-newsletter/08atwar-newsletter-superJumbo.jpg?quality=75&auto=webp'),
   ('Nature Conservation', 'Grassroots conservation movements are community-based initiatives that focus on protecting natural habitats, biodiversity, and ecosystems. These movements often involve local residents, environmentalists, and conservation organizations working together to preserve endangered species, prevent deforestation, and conserve natural resources. Grassroots conservation efforts may include habitat restoration projects, wildlife monitoring, community education and awareness campaigns, and advocacy for the creation of protected areas and sustainable land-use policies. These movements play a vital role in preserving biodiversity, promoting sustainable living practices, and ensuring the long-term health of ecosystems for future generations.', 'Location C', 2, '2023-10-20', 'https://d20x1nptavktw0.cloudfront.net/wordpress_media/2022/07/Blog-Image-50.jpg');

   
 







